### ISSUE TITLE
Atomicpasrley error

### ISSUE THREAD

**Issue by cruix89** [Jeeaaasus/youtube-dl#27]
hello friend, thanks again for this wonderful job. I'm having the error below, it happened after updating the docker and portainer to the latest version, could you give me some guidance on how it can be solved? thank you very much

ERROR: AtomicParsley was not found. Please install.

Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2102, in post_process

    files_to_delete, info = pp.run(info)

  File "/usr/lib/python3.8/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 93, in run

    raise EmbedThumbnailPPError('AtomicParsley was not found. Please install.')

youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: AtomicParsley was not found. Please install.

**Comment by Jeeaaasus** [comment]
that's odd..
Are you using the most recent image taged `latest`? (jeeaaasustest/youtube-dl:latest)

**Comment by cruix89** [comment]
yes, latest version, I have already recreated the containers and even reinstalled the docker to no sucess :(

**Comment by Jeeaaasus** [comment]
hmm, I can't recreate that, what happens if you run this on your docker host:
```
docker pull jeeaaasustest/youtube-dl && \
docker run -d --rm --name youtube-dl_test jeeaaasustest/youtube-dl && \
sleep 10 && \
docker exec youtube-dl_test atomicparsley --version && \
docker exec youtube-dl_test youtube-dl --version && \
docker stop youtube-dl_test
```

**Comment by cruix89** [comment]
Using default tag: latest
latest: Pulling from jeeaaasustest/youtube-dl
Digest: sha256:4473673feea8f91abb5a17c05f4ba52e5415dff0a5b90a63fab4af7db5fee503
Status: Image is up to date for jeeaaasustest/youtube-dl:latest
docker.io/jeeaaasustest/youtube-dl:latest
47f266a6aaacb5d104993bbb6a5ebfff82e1e0f722e938ac3c78a14da6ef9324
AtomicParsley version: 20210204.173043.0 92b5a49873fd35bcb8f6e70f500ea155699e389c (utf8)
2021.02.04.1
youtube-dl_test

**Comment by Jeeaaasus** [comment]
So that one works.
If you now re-make your containers it should work.

And I will investigate why this weirdness is happening..

**Comment by cruix89** [comment]
follow my arg file, it's very personalized for me, maybe some youtube dl function is going wrong?

--output "/downloads/%(uploader)s/%(title)s.%(ext)s"
--dateafter 00010101
--format best
--newline
--playlist-reverse
--no-cache-dir
--ignore-errors
--skip-unavailable-fragments
--no-continue
--merge-output-format mp4
--embed-thumbnail
--add-metadata
--sleep-interval 5

**Comment by cruix89** [comment]
but until yesterday everything was working perfectly :S

**Comment by PDSCi996** [comment]
> but until yesterday everything was working perfectly :S

The container has been normal a few days ago. The problem occurred yesterday. Then I deleted the container and installed the latest version. At the beginning, everything was normal. Later, I discovered that the problem occurred after restarting the container.

**Comment by Jeeaaasus** [comment]
I found the issue. The binary is no longer named 'AtomicParsley', for whatever reason it's been changed to 'atomicparsley'.

**Comment by Jeeaaasus** [comment]
Thanks for your help! @cruix89

**Comment by PDSCi996** [comment]
The latest container used, and the newly appeared bug logs are as follows.
The latest container used, and the newly appeared bug logs are as follows.
[download] Downloading video 10 of 30
[youtube] a5_y4yCR_oU: Downloading webpage
[youtube] a5_y4yCR_oU: Downloading MPD manifest
[youtube] a5_y4yCR_oU: Downloading thumbnail ...
[youtube] a5_y4yCR_oU: Writing thumbnail to: /downloads/ICDI/Mr. Qin Yonglong's Calligraphy Teaching Lecture Sixteenth Lecture on Running Script Calligraphy (6).jpg
[dashsegments] Total fragments: 222
[download] Destination: /downloads/ICDI/Mr. Qin Yonglong's Calligraphy Teaching Lecture Sixteenth Lecture on Running Scripts to Take Advantage of Changes (6).f248.webm
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError:'youtube-dl'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.8/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  
  return func(self, options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 99, in __bool__
    return any(self)
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 37, in _insert_installed
    for candidate in others:
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 78, in <genexpr>
    others = (
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 239, in iter_index_candidates
    candidate = self._make_candidate_from_link(
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 296, in __init__
    super(LinkCandidate, self).__init__(
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 307, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 503, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 253, in unpack_url
    file = get_http_url(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 130, in get_http_url
    from_path, conte

**Comment by Jeeaaasus** [comment]
@PDSCi996 This error is unrelated to the issue with AtomicParsley.
This issue is not specific to my image, I see the same error on a traditional install on my desktop.
You'll have to ask for help on the [youtube-dl project](https://github.com/ytdl-org/youtube-dl/issues).
