### ISSUE TITLE
download page error

### ISSUE THREAD

**Issue by cruix89** [Jeeaaasus/youtube-dl#28]
I'm also facing this error, in the older version of the past month of the script it didn't happen, now it does.

ERROR: Unable to download JSON metadata: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again')))
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/site-packages/youtube_dl/utils.py", line 2734, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)

already deletes all containers, uninstalled the docker and it didn't work :(

I looked for this python3.8 folder and strangely it doesn't exist on my server

thanks my friend

**Comment by Jeeaaasus** [comment]
could you please re-create this container with the env `-e youtubedl_debug=true`
and post the logs :)

**Comment by PDSCi996** [comment]
I am here to prompt
ERROR: AtomicParsley was not found. Please install.
Traceback (most recent call last):
   File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2102, in post_process
     files_to_delete, info = pp.run(info)
   File "/usr/lib/python3.8/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 93, in run
     raise EmbedThumbnailPPError('AtomicParsley was not found. Please install.')
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: AtomicParsley was not found. Please install.
Don't know if it helps

**Comment by cruix89** [comment]
> você poderia recriar este contêiner com o env `-e youtubedl_debug=true`
> e postar os logs :)

created, where are the logs?

**Comment by PDSCi996** [comment]
> > você poderia recriar este contêiner com o env `-e youtubedl_debug=true`
> > e postar os logs :)
> 
> created, where are the logs?

My log currently has only so much information about AtomicParsley.

**Comment by PDSCi996** [comment]
This new log I received today, I don’t know if it helps.

[generic] videos: Requesting header | stdout
WARNING: Could not send HEAD request to 3https://www.youtube.com/channel/UCw7HTQv0F4CB9zGRhqosYsg/videos: <urlopen error unknown url type: 3https> | stdout
[generic] videos: Downloading webpage | stdout
ERROR: Unable to download webpage: <urlopen error unknown url type: 3https> (caused by URLError('unknown url type: 3https')) | stdout
File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 632, in _request_webpage | stdout
    return self._downloader.urlopen(url_or_request) | stdout
File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2275, in urlopen | stdout
    return self._opener.open(req, timeout=self._socket_timeout) | stdout
File "/usr/lib/python3.8/urllib/request.py", line 525, in open | stdout
    response = self._open(req, data) | stdout
File "/usr/lib/python3.8/urllib/request.py", line 547, in _open | stdout
    return self._call_chain(self.handle_open, 'unknown', | stdout
File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain | stdout
    result = func(*args) | stdout
File "/usr/lib/python3.8/urllib/request.py", line 1421, in unknown_open | stdout
    raise URLError('unknown url type: %s' % type) | stdout

**Comment by cruix89** [comment]
the same error here =(

**Comment by Jeeaaasus** [comment]
@PDSCi996 You have a bad url, there's a '3' that should not be there.
```
request to 3https://www.youtube.com/channel/UCw7HTQv0F4CB9zGRhqosYsg/videos: <urlopen error unknown url type: 3https>
```

**Comment by Jeeaaasus** [comment]
@cruix89 
Are you still having this issue?
How often?

It looks like your container couldn't find the webpage, maybe your internet dropped, or your network is miss-configured.

**Comment by cruix89** [comment]
apparently now it is only downloading the first page, with the first 30 videos of the channel, and no limitation is set in args

**Comment by cruix89** [comment]
not giving error, but just ignoring the other pages of the channel

**Comment by cruix89** [comment]
hello friend, today the script is working perfectly, downloading all the pages of the channels and not showing any error. I think everything is normal now. Thank you very much for donating your time to help us. Blessings

**Comment by Jeeaaasus** [comment]
👍 😊
Feel free to open issues if you have problems in the future!
